from django.conf.urls import patterns,include, url

urlpatterns = [
		url(r'^$','netlyst.views.home_page'),
		url(r'^login$', 'netlyst.views.login_page'),
		url(r'^logout$', 'django.contrib.auth.views.logout_then_login', name = 'logout'),
		url(r'^signup$','netlyst.views.signup_page', name = 'signup'),
		url(r'^profile$', 'netlyst.views.profile', name = 'profile'),

		url(r'^global$', 'netlyst.views.global_page',name = 'global'),
		url(r'^add_post$', 'netlyst.views.add_post',name = 'add_post'),
		url(r'^profile/(?P<id>\d+)$','netlyst.views.viewprofile',name = 'viewprofile'),
		url(r'^editinfo$','netlyst.views.edit_info',name = 'edit'),
		url(r'^photo/(?P<id>\d+)$','netlyst.views.get_photo',name = 'photo'),
		url(r'^visitorinfo(?P<id>\d+)$','netlyst.views.visitor', name = 'visitorinfo'),
		url(r'^confirmmessage$','netlyst.views.passwordchangeconfirm',name = 'confirmmessage'),
		url(r'^confirm/(?P<token>[a-zA-Z0-9_\-]+)/(?P<username>[a-zA-Z0-9_]+)/$','netlyst.views.confirm',name ='confirm'),

		url(r'^groupstream$', 'netlyst.views.groupstream', name='groupstream'),
		url(r'^create_group$', 'netlyst.views.create_group', name='create_group'),
		url(r'^get_group/(?P<id>\d+)$', 'netlyst.views.get_group', name='get_group'),
		url(r'^group_post/(?P<id>\d+)$', 'netlyst.views.group_post', name='group_post'),
		url(r'^join/(?P<id>\d+)$','netlyst.views.join', name='join'),
   	url(r'^quit/(?P<id>\d+)$','netlyst.views.quit', name='quit'), 

   	url(r'^follow/(?P<id>\d+)$','netlyst.views.follow', name='follow'),
   	url(r'^unfollow/(?P<id>\d+)$','netlyst.views.unfollow', name='unfollow'),

   	url(r'^follow_page/(?P<id>\d+)$','netlyst.views.follow_page', name='follow_page'),
   	url(r'^view_position$', 'netlyst.views.view_position', name='view_position'),
   	url(r'^save_user_position/(?P<id>\d+)$', 'netlyst.views.save_user_position', name='save_user_position'),
   	url(r'^messages/', include('django_messages.urls')),
   	url(r'^postphoto/(?P<id>\d+)$','netlyst.views.get_postphoto',name = 'postphoto'),
   	url(r'^report_spam/(?P<id>\d+)$', 'netlyst.views.report_spam', name='report_spam'),

   	url(r'^word_cloud/', include('word_cloud.urls')),
   	url(r'^post_pos_val/(?P<id>\d+)$','netlyst.views.post_pos_val',name = 'post_pos_val'),
   	url(r'^like/(?P<id>\d+)$','netlyst.views.like',name='like'),
   	url(r'^unlike/(?P<id>\d+)$','netlyst.views.unlike',name='unlike'),
   	url(r'^get_group_info/(?P<id>\d+)$','netlyst.views.get_group_info',name='get_group_info'),
   	url(r'^get_group_info_all$','netlyst.views.get_group_info_all',name='get_group_info_all'),
   	url(r'^test$','netlyst.views.test',name='test'),
   	url(r'^search_user$','netlyst.views.search_user', name='searchUser'),
   	url(r'^groupphoto/(?P<id>\d+)$','netlyst.views.get_group_photo', name='groupphoto'),
   	url(r'^editgroup/(?P<id>\d+)$','netlyst.views.edit_group', name="edit_group"),
      url(r'^someview$','netlyst.views.some_view',name="someview"),
      url(r'^age_distribution$','netlyst.views.age_distribution',name="age_distribution"),
      url(r'^gender_distribution$','netlyst.views.gender_distribution',name="gender_distribution"),
      url(r'^gender$','netlyst.views.gender',name="gender"),
      url(r'^global_distribution$','netlyst.views.global_distribution',name="global_distribution"),
      
      url(r'^calender/(?P<id>\d+)$','netlyst.views.calender',name="calender"),
      url(r'^get_follower_graph/(?P<id>\d+)$','netlyst.views.get_follower_graph',name="get_follower_graph"),
      url(r'^get_followee_graph/(?P<id>\d+)$','netlyst.views.get_followee_graph',name="get_followee_graph"),
      url(r'^album/(?P<id>\d+)$','netlyst.views.album',name = 'album'),
      url(r'^follower_visual/(?P<id>\d+)$','netlyst.views.follower_visual',name='follower_visual'),
      url(r'^followee_visual/(?P<id>\d+)$','netlyst.views.followee_visual',name='followee_visual'),
      url(r'^post_record$','netlyst.views.post_record',name="post_record"),
]
